export default {
  GET_NODE_BOARD_BY_ID_REQUEST: '@board/GET_NODE_BOARD_BY_ID_REQUEST',
  GET_NODE_BOARD_BY_ID_SUCCESS: '@board/GET_NODE_BOARD_BY_ID_SUCCESS',
  GET_NODE_BOARD_BY_ID_FAILURE: '@board/GET_NODE_BOARD_BY_ID_FAILURE',

  GET_USER_BOARD_BY_ID_REQUEST: '@board/GET_USER_BOARD_BY_ID_REQUEST',
  GET_USER_BOARD_BY_ID_SUCCESS: '@board/GET_USER_BOARD_BY_ID_SUCCESS',
  GET_USER_BOARD_BY_ID_FAILURE: '@board/GET_USER_BOARD_BY_ID_FAILURE',

  GET_SERVICE_ORDERS_BY_USER_ID_REQUEST: '@board/GET_SERVICE_ORDERS_BY_USER_ID_REQUEST',
  GET_SERVICE_ORDERS_BY_USER_ID_SUCCESS: '@board/GET_SERVICE_ORDERS_BY_USER_ID_SUCCESS',
  GET_SERVICE_ORDERS_BY_USER_ID_FAILURE: '@board/GET_SERVICE_ORDERS_BY_USER_ID_FAILURE',

  GET_SERVICE_ORDERS_BY_NODE_ID_REQUEST: '@board/GET_SERVICE_ORDERS_BY_NODE_ID_REQUEST',
  GET_SERVICE_ORDERS_BY_NODE_ID_SUCCESS: '@board/GET_SERVICE_ORDERS_BY_NODE_ID_SUCCESS',
  GET_SERVICE_ORDERS_BY_NODE_ID_FAILURE: '@board/GET_SERVICE_ORDERS_BY_NODE_ID_FAILURE',

  GET_SERVICE_ORDER_BY_ID_REQUEST: '@board/GET_SERVICE_ORDER_BY_ID_REQUEST',
  GET_SERVICE_ORDER_BY_ID_SUCCESS: '@board/GET_SERVICE_ORDER_BY_ID_SUCCESS',
  GET_SERVICE_ORDER_BY_ID_FAILURE: '@board/GET_SERVICE_ORDER_BY_ID_FAILURE',

  CLEAR: '@board/CLEAR',
}
